services:
  base-datos:
    image: mysql:8.0
    ports:
      - 3307:3306
    volumes:
      - ./src/main/resources/database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: apis 
